# Generated by Django 5.0.7 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('sOrb', models.CharField(max_length=6)),
                ('license', models.FileField(upload_to='')),
            ],
        ),
    ]
