# Generated by Django 5.0.7 on 2024-07-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_license_info__license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='_license',
            new_name='file_license',
        ),
    ]
